---
- name: Playbook for tasks
  hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Create repo
      copy: 
        src: r1.soft.repo
        dest: /etc/yum.repos.d/

    - name: Install agent
      package: 
        name: serverbackup-enterprise-agent
        state: present

    - name: Get Key
      shell: "r1soft-setup --get-key http://18.202.176.64:8080"