---
- name: Playbook for sec groups
  hosts: localhost
  tasks: 
    - name: VPC for Class
      ec2_vpc_net:
        name: Module_dev2
        cidr_block: 10.10.0.0/16
        region: eu-west-3
        tags:
          Class: Ansible
          Task: VPC
      