---
- name: Playbook for Provisioning
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
    - ec2:
        key_name: ansible222
        instance_type: "{{instance_type}}"
        image: ami-0eab3a90fc693af19
        count: "{{count}}"
        vpc_subnet_id: "{{vpc_subnet_id}}"
        assign_public_ip: yes
        region: "{{region}}"
