---
- name: Playbook for creating vpc
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
    - name: Create subnet for database servers
      ec2_vpc_subnet:
        state: present
        region: eu-west-2
        az: eu-west-2a
        vpc_id: vpc-0df90bbb045d74bf4
        cidr: 10.10.1.0/24
        resource_tags:
          Name: Private Subnet
      register: private_subnet
    - name: Create subnet for database servers
      ec2_vpc_subnet:
        state: present
        region: eu-west-2
        az: eu-west-2b
        vpc_id: vpc-0df90bbb045d74bf4
        cidr: 10.10.2.0/24
        resource_tags:
          Name: Public Subnet
      register: public_subnet    
    - name: example using security group rule descriptions
      ec2_group:
        name: ssh and httpd open
        description: sg with rule descriptions
        vpc_id: vpc-0df90bbb045d74bf4 
        region: eu-west-2
        rules:
          - proto: tcp
            ports:
              - 80
              - 22
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all on port 80
    
    - name: create launch config
      ec2_lc:
        name: my_new_lc
        image_id: ami-0058eac8cae55e22e
        key_name: mywindows
        region: eu-west-2
        security_groups: sg-0628115120201dcc7
        instance_type: t2.micro
        assign_public_ip: yes

    - ec2_asg:
        name: myasg
        load_balancers: New ELB
        launch_config_name: my_new_lc
        health_check_period: 60
        health_check_type: ELB
        min_size: 3
        max_size: 12
        desired_capacity: 3
        vpc_zone_identifier: 
          - subnet-0c169b89eb307ebde
          - subnet-0c826e80f68a5ec28
        region: eu-west-2
        tags:
          - environment: production
            propagate_at_launch: no 
    
    - local_action:
        module: ec2_elb_lb
        name: New ELB
        scheme: internal
        state: present
        instance_ids:
          - i-0603275ab04222954
        security_group_ids: sg-0628115120201dcc7
        region: eu-west-2
        zones: eu-west-2b
        subnets: 
          - subnet-0c169b89eb307ebde
          - subnet-0c826e80f68a5ec28
        purge_instance_ids: true
        listeners:
          - protocol: http
            load_balancer_port: 80
            instance_port: 80            