---
- name: Playbook for creating vpc
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
    - name: Create subnet for database servers
      ec2_vpc_subnet:
        state: present
        region: eu-west-2
        az: eu-west-2a
        vpc_id: vpc-0df90bbb045d74bf4
        cidr: 10.10.1.0/24
        resource_tags:
          Name: Private Subnet
      register: private_subnet
        
