---
- name: Playbook for creating vpc
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
    - name: create a VPC with dedicated tenancy and a couple of tags
      ec2_vpc_net:
        name: Enver's Vpc
        cidr_block: "{{cidr_block range}}"
        region: "{{eu-west-2}}"
        tags:
          module: ec2_vpc_net
          this: works
