---
- name: Playbook for sec groups
  hosts: localhost
  tasks:
    - name: Create public subnet 1
      ec2_vpc_subnet:
        state: present
        vpc_id: vpc-0b2627c7de857e9e9
        region: eu-west-3
        cidr: 10.0.101.16/28
        tags:
          Name: Web Subnet1
      register: Web_subnet1

    - name: Create public subnet 2
      ec2_vpc_subnet:
        state: present
        vpc_id: vpc-0b2627c7de857e9e9
        region: eu-west-3
        cidr: 10.0.102.16/28
        tags:
          Name: Web Subnet2
      register: Web_subnet2

    - name: Create public subnet 3
      ec2_vpc_subnet:
        state: present
        vpc_id: vpc-0b2627c7de857e9e9
        region: eu-west-3
        cidr: 10.0.103.16/28
        tags:
          Name: Web Subnet3
      register: Web_subnet3  